name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: scripts/buildprod.sh
      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
      - name: Use gcloud CLI
        run: gcloud info
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/notely-486023/notely-ar-repo/notely:latest .
      - name: Push to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/notely-486023/notely-ar-repo/notely:latest
      - name: Smoke test
        run: |
          ./notely &
          sleep 2
          curl -sf http://localhost:8080/v1/healthz || exit 1
          pkill notely || true
        env:
          PORT: "8080"